server:
  port: ${PORT:8086}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  cloud:
    gateway:
      routes:
      - id: qs
        uri: lb://backing-service:8088
        predicates:
        - Path=/qs/**
        filters:
        - RewritePath=/qs, /
      - id: quote
        uri: lb://backing-service:8088
        predicates:
        - Path=/quote
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/defaultquote
        - RewritePath=/quote, /quotes/random

#        uri: lb://backing-service:8088

# Misc
quote: "Whatever the question, coffee is always the answer."